### ISSUE TITLE
gdbinit does not support gdb tui

### ISSUE THREAD

**Issue by beyondjjw** [gdbinit/Gdbinit#32]
gdb -tui 
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
---Type <return> to continue, or q <return> to quit---
For help, type "help".
Type "apropos word" to search for commands related to "word".

warning: ~/.gdbinit.local: 没有那个文件或目录
^[[31mgdb$ ^[[0m

**Comment by gdbinit** [comment]
Not a user of gdb tui so I have no idea about it.

**Comment by Ferenc-** [comment]
IMHO this issue can be closed.
I can confirm that gdbinit does support gdb tui.
What @beyondjjw posted here is basically the output of a quite normal startup.
The Chinese warning only says: "~/.gdbinit.local: No such file or directory" which has nothing to do with the TUI support at all. 
The piece of garbled output is the colored gdb prompt which doesn't work so well with the libncurses library used by the TUI, but as of https://github.com/gdbinit/Gdbinit/commit/2c7955b4e5d6cd5a71c6c15f6386f385f8cbfbd5 you can turn it off with the `disablecolorprompt` command. But even before that you could have just redefined the prompt.
So I think now users can just use the command and everything should work fine.
